spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.248.100:8848
    gateway:
      routes:
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/app/product/**
          filters:
            - RewritePath=/app/(?<segment>/?.*),/$\{segment}
        - id: third-route
          uri: lb://mall-third
          predicates:
            - Path=/app/third/**
          filters:
            - RewritePath=/app/third/(?<segment>/?.*),/$\{segment}
        - id: member-route
          uri: lb://mall-member
          predicates:
            - Path=/app/member/**
          filters:
            - RewritePath=/app/(?<segment>/?.*),/$\{segment}
        - id: ware-route
          uri: lb://mall-ware
          predicates:
            - Path=/app/ware/**
          filters:
            - RewritePath=/app/(?<segment>/?.*),/$\{segment}
        - id: app_route
          uri: lb://renren-fast
          predicates:
            - Path=/app/**
          filters:
            - RewritePath=/app/(?<segment>/?.*),/renren-fast/$\{segment}
server:
  port: 8070