spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.248.100:8848
    gateway:
      routes:
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/app/product/**,/hello
          filters:
            - RewritePath=/app/(?<segment>/?.*),/$\{segment}
        - id: third-route
          uri: lb://mall-third
          predicates:
            - Path=/app/third/**
          filters:
            - RewritePath=/app/third/(?<segment>/?.*),/$\{segment}
        - id: member-route
          uri: lb://mall-member
          predicates:
            - Path=/app/member/**
          filters:
            - RewritePath=/app/(?<segment>/?.*),/$\{segment}
        - id: ware-route
          uri: lb://mall-ware
          predicates:
            - Path=/app/ware/**
          filters:
            - RewritePath=/app/(?<segment>/?.*),/$\{segment}
        - id: app_route
          uri: lb://renren-fast
          predicates:
            - Path=/app/**
          filters:
            - RewritePath=/app/(?<segment>/?.*),/renren-fast/$\{segment}
        - id: msbmall_host_route1
          uri: lb://mall-product
          predicates:
            - Host=msb.mall.com
        - id: msbmall_host_route2
          uri: lb://mall-product
          predicates:
            - Host=msb.item.com
        - id: msbmall_host_route3
          uri: lb://mall-search
          predicates:
            - Host=msb.search.com
        - id: msbmall_host_route4
          uri: lb://mall-auth
          predicates:
            - Host=msb.auth.com
server:
  port: 8070