# 数据库的连接新
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.248.100:8848
  application:
    name: mall-search
  # 统一的全局的--设置服务器响应给客户端的日期时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  session:
    store-type: redis
    redis:
      namespace: spring:session
  redis:
    host: 192.168.248.100
    port: 6379
server:
  port: 8090