spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.248.100:8848
    alicloud:
      access-key: your-ak
      secret-key: your-sk
      oss:
        endpoint: '***'
        bucket: mashibing-mall
      sms:
        host: https://dfsns.market.alicloudapi.com
        path: /data/send_sms
        method: POST
        appCode: 52b846ac1f574a2e8a74e2df7585c24c

server:
  port: 8090