spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.248.100:8848

server:
  port: 8090

alibaba:
  cloud:
    access-key: your-ak
    secret-key: your-sk
  oss:
    endpoint: '***'